name: Continuous Integration
on: [push, pull_request, merge_group]

env:
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run `pre-commit` checks
        uses: pre-commit/action@v3.0.0
        with:
          components: rustfmt

  test:
    name: Test
    needs: 'lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets --all-features --no-deps
      - run: cargo doc --workspace --no-deps
      - run: cargo test --workspace --no-run
      - run: cargo test --workspace --no-fail-fast
